let data=[

    {  
       ProductId:"mutton_101",
        image:"https://dao54xqhg9jfa.cloudfront.net/OMS-ProductMerchantdising/04aefdb4-bc21-21b0-8a2f-79be7f9d3eb5/original/Goat-Boneless-Hero-Shot.jpg?format=webp",
        Title:"Goat - Boneless",
        productPagedetails:"Our medium-sized boneless pieces are cut from the hind legs of healthy, farm-raised goats. These juicy dark portions of meat are fat-trimmed and have a moderate to strong flavour with a soft, moist texture. In terms of nutrients, these meat portions are rich in proteins, vitamins and minerals.ProductIdeal for pan-fried dishes as well as curries, these meat portions are perfect if you prefer more flesh and no bones in your meat. Buy Boneless Goat Meat online from Licious and get it delivered at your doorstep.",
        Details:"Chunky, even pieces of fat-trimmed, boneless goat meat from the hind legs",
        Netwt:"500gms", 
        Gross:"758gms",
        MRP:"725",
        CutType:"Boneless",
       image1:"https://dao54xqhg9jfa.cloudfront.net/OMS-ProductMerchantdising/4623c042-9137-f982-5947-c71a1c0050ad/original/Goat-Boneless-No-of-Piece-Shot.jpg?format=webp",
       image2:"https://dao54xqhg9jfa.cloudfront.net/OMS-ProductMerchantdising/86fae83b-4057-62e7-e2e1-f870a13771bb/original/WhatsApp_Image_2022-06-08_at_1.53.44_PM_(1).jpeg?format=webp",
    },
    {  
       ProductId:"mutton_102", 
        image:"https://dao54xqhg9jfa.cloudfront.net/OMS-ProductMerchantdising/25caa9c3-6beb-32d5-1af5-a4e39b98a629/original/Goat-Mince_Keema--Hero-Shot.jpg?format=webp",
        Title:"Goat - Mince (Keema)",
        productPagedetails:"Licious Goat Mince is obtained from cuts of boneless goat meat that has been ground perfectly. Goat mince is also known as keema and has a fine-grained, delicate texture, with a robust flavour. Obtained from grass-fed, humanely raised goats, it is rich in minerals and vitamins and isProductIdeal for kebabs, keema masala or keema pulao. Order Goat Mince online from Licious to prepare delectable kebabs at home.",
        Details:"Ground goat meat,ProductIdeal for kebabs, cutlets & more",
        Netwt:"450gms", 
        Gross:"562gms",
        MRP:"525",
        BestSuitedFor:"Biryani",
       image1:"https://dao54xqhg9jfa.cloudfront.net/OMS-ProductMerchantdising/95283b72-e0ef-1612-b05d-33893d5ea51b/original/1634748510.png?format=webp",
       
    },
    {  
       ProductId:"mutton_103", 
        image:"https://dao54xqhg9jfa.cloudfront.net/OMS-ProductMerchantdising/fd8d45d1-247d-2fd7-d994-51fc0769bc04/original/Lean-Goat-Curry-Cut-(Small,-16-20-Pieces)-Hero-Shot.jpg?format=webp",
        Title:"Lean Goat Curry Cut - Small Pieces",
        productPagedetails:"Our Lean Goat Curry Cut is a mix of bone-in & boneless pieces, from the ribs, neck, and legs which have been expertly butchered by our meat technicians.Our Lean Goat Curry Cut is a natural source of protein and has been fat-trimmed which makes it an excellent choice for curries.The meat is free from antibiotic residue and is allowed to rest so it is tender. Our mutton comes from government-approved partners and passes through over 150 quality checks to ensure it is safe. We also use vacuum packaging which keeps the meat safe and fresh. Order Lean Goat Curry Cut online from Licious and get it delivered to your home.",
        Details:"Trimmed bone-in & boneless pieces",
        Netwt:"450gms", 
        Gross:"979gms",
        MRP:"479",
        MuttonType:"Goat",
       image1:"https://dao54xqhg9jfa.cloudfront.net/OMS-ProductMerchantdising/f0b3a9e9-2ec7-e3fb-5efb-ceca52e4fccc/original/1634748510.png?format=webp",
       
    },
    {  
       ProductId:"mutton_104", 
        image:"https://dao54xqhg9jfa.cloudfront.net/OMS-ProductMerchantdising/9db46fc7-7b5c-acb2-59c9-08f3d9c17165/original/Rich-Goat-Curry-Cut-(Small---19-to-21-Pieces)--Hero-Shot.jpg?format=webp",
        Title:"Rich Goat Curry Cut - Small Pieces",
        productPagedetails:"longone",
        Details:"Bite-sized cuts of rich goat meat on the bone, from the ribs, shoulder and loins.",
        Netwt:"450gms", 
        Gross:"529gms",
        MRP:"435",
        BoneType:"Boneless",
       image1:"https://dao54xqhg9jfa.cloudfront.net/OMS-ProductMerchantdising/eceb33b7-437f-b453-1529-037dbc631130/original/Rich-Goat-Curry-Cut-(Small---19-to-21-Pieces)---pr_2s9jxdmnvu2---No-of-Piece-Shot.jpg?format=webp",
       image2:"https://dao54xqhg9jfa.cloudfront.net/OMS-ProductMerchantdising/1d5ab89b-cad9-e709-61ff-86b8c0192df4/original/1634748510.png?format=webp",
    },
    {  
       ProductId:"mutton_105", 
        image:"https://d2407na1z3fc0t.cloudfront.net/prodDev/pr_576360a8b87f1/12/prod_image/1634625124.1345--2021-10-1912:02:04--1818?format=webp",
        Title:"Mutton Liver Chunks",
        productPagedetails:"Known for its intense and rich flavour, mutton liver (also known as Kaleji) is best enjoyed in a simple preparation such as Sauteed Liver and Onions, spicy Kaleji Fry, Moroccan Fried Liver etc. This meat is best cooked in a pan or oven and should be cooked until done and light pink in the centre. Do not overcook it!Our mutton comes from government-approved partners and passes through over 150 quality plus quality checks to ensure it is safe. The meat is free from antibiotic residue and is cut & cleaned by experts. It is then hygienically packed & vacuum-sealed to preserve its freshness.",
        Details:"Cleaned, trimmed &amp; tender cook up delicious meals with fresh cuts of mutton liver!",
        Netwt:"250", 
        Gross:"250",
        MRP:"195",
        BoneType:"Boneless",
    },
    {  
       ProductId:"mutton_106", 
        image:"https://dao54xqhg9jfa.cloudfront.net/ProductMerchantdising/a5f18934-6b06-a66e-1fb7-1db577ef59b6/original/1583443390.2963--2020-03-0602_53_10--472.jpeg?format=webp",
        Title:"Goat Ribs and Chops",
        productPagedetails:"Mutton Ribs and Chops are mainly cut from the rack of the Goat, which is the upper centre part of the goat's body. The package also includes cuts from the shoulders, ribs and loins. Mutton Chops are T-bone steaks that give you tender meat once cooked evenly. Goat Ribs and Chops are strong in flavour and tender in texture. These are also the fattier cuts of the Goat. Rich in proteins and minerals, Goat Ribs and Chops are an excellent choice for barbecuing or making a curry. Buy Goat Ribs and Chops online from Licious and get home delivery. ",
        Details:"Perfectly cut, mix of 8-9 tender goat ribs and juicy chops to cook a quick weekday dinner or fire up the grill for a scrumptious weekend menu.",
        Netwt:"500", 
        Gross:"588",
        MRP:"450",
        BestSuitedFor:"Pan Fry",
       image1:"https://d2407na1z3fc0t.cloudfront.net/prodDev/pr_4dmjfl18hj2/12/prod_image/1632416887.7376--2021-09-2322:38:07--905?format=webp",
    },
    {  
       ProductId:"mutton_107",
        image:"https://dao54xqhg9jfa.cloudfront.net/OMS-ProductMerchantdising/5cb716c9-de60-0b60-a7d2-394898281dbe/original/WhatsApp_Image_2022-06-08_at_3.29.42_PM.jpeg?format=webp",
        Title:"Goat Curry Cut - Shoulder",
        productPagedetails:"Cut from the forequarter, our Goat Shoulder Curry Cut offers both bone-in and boneless pieces. The curry cut also offers nutrient-dense shank pieces from the Goat. These pieces are strong in flavour and juicy in texture.ProductIdeal for slow cooking, this cut is the perfect choice to make a delicious curry. Order Goat Shoulder Curry Cut online from Licious and get it delivered at your doorstep.     ",
        Details:"Evenly cut, juicy, bone-in and boneless pieces of goat meat from the shoulders of goat.",
        Netwt:"500gms", 
        Gross:"833gms",
        MRP:"609",
        MuttonType:"Goat",
       image1:"https://dao54xqhg9jfa.cloudfront.net/OMS-ProductMerchantdising/b4608945-f3f4-1e30-da40-0f9cba26b3bc/original/WhatsApp_Image_2022-06-08_at_3.29.47_PM.jpeg?format=webp",
       image2:"https://dao54xqhg9jfa.cloudfront.net/OMS-ProductMerchantdising/2187ed35-4ad1-2a1e-a530-a262b958f364/original/WhatsApp_Image_2022-06-08_at_1.53.44_PM_(2).jpeg?format=webp",
    },
    
    {  
       ProductId:"mutton_108",
        image:"https://dao54xqhg9jfa.cloudfront.net/OMS-ProductMerchantdising/0f1f2bf6-2eee-ba96-544b-fd378cb40883/original/WhatsApp_Image_2022-06-08_at_1.47.04_PM.jpeg?format=webp",
        Title:"Goat Biryani Cut",
        productPagedetails:"Licious Goat Biryani Cut has meaty chunks of bone-in and boneless goat meat. They have been expertly butchered by our meat technicians and turn soft and juicy when cooked, adding richness to your lip-smacking biryanis.These small, tender pieces areProductIdeal for a variety of dishes, from slow-cooked curries, pan-fried meals or delicious stews. Pro-tip: Low heat will help to bring out the flavours of the meat and prevent overcooking.Our Goat Biryani Cut is sourced from pasture-raised and sourced from government approved partners. Once cut, our meat is fat-trimmed, cleaned, and hygienically vacuum packed.",
   
        Details:"Bone-in and boneless goat chunks crafted to create the rich flavour essential for biryani.",
        Netwt:"500gms", 
        Gross:"666gms",
        MRP:"497",
        MuttonType:"Goat",
      
    },
    {  
       ProductId:"mutton_109",
        image:"https://dao54xqhg9jfa.cloudfront.net/OMS-ProductMerchantdising/3550630d-5620-4375-46ed-f072105ead7d/original/WhatsApp_Image_2022-06-08_at_4.55.00_PM.jpeg?format=webp",
        Title:"Lamb Curry Cut - Shoulder",
        productPagedetails:"Evenly cut from the top front leg, our medium-sized, bone-in Lamb Shoulder Curry Cuts are one of the juiciest meat portions. Obtained from healthy lambs raised in open pastures, they are rich in proteins, vitamin B12, zinc, and iron. High on flavour with a firm texture and a little more fat as compared to leaner cuts, they areProductIdeal for slow-cooked curries. Order Lamb Shoulder Curry Cuts online and get them home delivered.",
        Details:"shortone",
        Netwt:"500gms", 
        Gross:"833gms",
        MRP:"594",
        CutTyoe:"Sholder Cut",
       image1:"https://dao54xqhg9jfa.cloudfront.net/OMS-ProductMerchantdising/e97d02fd-c610-68b4-18ad-c2893d5bceee/original/WhatsApp_Image_2022-06-08_at_4.55.03_PM.jpeg?format=webp",
       image2:"https://dao54xqhg9jfa.cloudfront.net/OMS-ProductMerchantdising/5c91e839-0fe7-05de-d573-d13af00755c0/original/WhatsApp_Image_2022-06-08_at_4.39.21_PM_(1).jpeg?format=webp",
    },
    {  
       ProductId:"mutton_110", 
        image:"https://dao54xqhg9jfa.cloudfront.net/OMS-ProductMerchantdising/293949ce-fd64-aae0-ee6e-bc367da118a2/original/Goat-Tail--Hind-Meat-Hero-Shot.jpg?format=webp",
        Title:"Goat Tail - Hind Meat",
        productPagedetails:"Thoroughly cleaned and cut into even pieces, Goat Tail is perfect for making comforting soups and is even enjoyed as a deep-fried treat! Order Goat Tail online from Licious, obtained from grass-fed, humanely raised goats, and prepare delicious dishes.",
        Details:"Fresh, meaty cuts of goat tail.",
        Netwt:"200", 
        Gross:"263",
        MRP:"279",
        Delivery:"Express Delivery",
       image1:"https://dao54xqhg9jfa.cloudfront.net/OMS-ProductMerchantdising/e3f34580-95d5-3465-bd90-3eb3cb47f6f7/original/Goat-Tail--Hind-Meat---No-of-Piece-Shot.jpg?format=webp",
       image2:"https://dao54xqhg9jfa.cloudfront.net/OMS-ProductMerchantdising/d6a133c4-b330-b418-1709-4831b3686136/original/1634748510.png?format=webp",
    },
    {  
       ProductId:"mutton_111", 
        image:"https://d2407na1z3fc0t.cloudfront.net/prodDev/pr_15tkn4fwbul/1/prod_image/1619619092.3213--2021-04-2819:41:32--738",
        Title:"Lamb Tail - Hind Meat.",
        productPagedetails:"Lamb Tails are enjoyed in many ways - from being grilled till the meat falls off the bone to being sauteed with a variety of spices. It offers a rich, meaty flavour. Order Lamb Tail online from Licious to prepare delicious dishes.",
        Details:"Fresh meaty cuts of lamb tail.",
        Netwt:"200", 
        Gross:"263",
        MRP:"279",
        PackSize:"Large Pack",
       image1:"https://d2407na1z3fc0t.cloudfront.net/prodDev/pr_15tkn4fwbul/1/prod_image/1632409405.3597--2021-09-2320:33:25--1818",
      
    },
    {  
       ProductId:"mutton_112", 
        image:"https://dao54xqhg9jfa.cloudfront.net/OMS-ProductMerchantdising/e0b1a9c9-40dc-c06f-3319-6ea7d5abe917/original/Goat-Fat--Hero-Shot.jpg?format=webp",
        Title:"Goat Fat",
        productPagedetails:"Perfect to be used as cooking fat, Goat Fat boosts energy metabolism. To render: cook over low heat until completely melted. Use rendered goat fat in the preparation of hot dishes - such as roasting or searing vegetables and meat.",
        Details:"Cleaned, rich strips of goat fat.",
        Netwt:"200", 
        Gross:"211",
        MRP:"80",
       image1:"https://dao54xqhg9jfa.cloudfront.net/OMS-ProductMerchantdising/d3f29245-2b6e-32c9-f4c1-7cff2205db1d/original/1634748510.png?format=webp",
      
    },
    ] 