let data=[
    {
    ProductId:"cook101",
    image:"https://dao54xqhg9jfa.cloudfront.net/OMS-ProductMerchantdising/59f81a69-ae84-72e8-b310-92678caa5a4b/original/Crispy-Chicken-Wings-Tag_(1).jpg?format=webp",
    Title:"Crispy Chicken Wings | Ready To Cook",
    productPagedetails:"Craving crispy, juicy wings but don't have the time to make them from scratch? Licious Crispy Chicken Wings are what you need! Marinated in hot chilli seasoning, the wings are then coated in batter & covered in panko bread crumbs. This means that all you have to do is to deep-fry these wings & it's ready within 8 minutes! Have the crispy, juicy wings with a squeeze of lime or paired with your favourite condiment.",
    Details:"Chicken wings marinated in spices & coated in panko crumbs.",
    Netwt:"225gms", 
    Pieces:"7-8",
    MRP:"99",
    Menu:"Wings",
   image1:"https://dao54xqhg9jfa.cloudfront.net/OMS-ProductMerchantdising/710f58cb-052c-7e81-a97b-3962aff07022/original/Crispy-Chicken-Wings-Hero-Shot-Cooked.jpg?format=webp",
   
},
{
    ProductId:"cook102",
    image:"https://d2407na1z3fc0t.cloudfront.net/prodDev/pr_fhijtgw0ctk/1/prod_display_image/1613378266.2769--2021-02-1514:07:46--738?format=webp",
    Title:"Classic Chicken Soup Bones",
    productPagedetails:"There's nothing better than fresh, homemmade broth to make delicious stews, soups and more!The bones are thoroughly cleaned and lightly seasoned to make things easier and help you cut down on prep time! Add them to water and boil to create a mild and nutrient-rich soup, or add additional spices to enhance their flavour. ",
    Details:"11-12 pieces of cleaned bones for chicken stock",
    Netwt:"105", 
    Pieces:"11-12",
    MRP:"250",
    Menu:"Marinades",
   image1:"https://d2407na1z3fc0t.cloudfront.net/prodDev/pr_fhijtgw0ctk/1/prod_image/1634207959.5014--2021-10-1416:09:19--905?format=webp",
   
},
{
    ProductId:"cook103",
    image:"https://dao54xqhg9jfa.cloudfront.net/OMS-ProductMerchantdising/8c1add24-1370-e120-1e27-fc64fb4efeb7/original/Amritsari-Fish-Ready_to_Cook.jpg?format=webp",
    Title:"Achari Fish Tikka | Ready to Cook",
    productPagedetails:"",
    Details:"Make this popular street food from Amritsar at home in under 10 minutes! Boneless cubes of fresh basa fish, coated in a tangy & spicy batter of ajwain (carrom seed), white vinegar, red chillies, raw mango and other herbs & spices. Licious Amritsari fish is ready to cook, so all you need to do is deep fry it for a few minutes until golden brown and serve with a sprinkle of chaat masala & squeeze of lime. ",
    Netwt:"300gms", 
    Pieces:"7-10",
    MRP:"279",
    MeatType:"Fish",
   image1:"https://dao54xqhg9jfa.cloudfront.net/OMS-ProductMerchantdising/4920ed07-e050-7326-e282-d12a42a78067/original/Cooking-instruction-All.PNG?format=webp",
   image2:"https://dao54xqhg9jfa.cloudfront.net/OMS-ProductMerchantdising/b67b7896-4c7a-33e8-a4ef-3f05de4aeff3/original/Marinades_Bangalore-01.jpg?format=webp"
},
{
    ProductId:"cook104",
    image:"https://dao54xqhg9jfa.cloudfront.net/OMS-ProductMerchantdising/54a88df7-f669-140f-230c-92f1f1db07ff/original/Crispy-Prawns-_-Tagjpg.jpg?format=webp",
    Title:"Crispy Prawns | Ready to Cook",
    productPagedetails:"Crumb-coated, crispy prawns that cook within 8 minutes! A perfect movie-time snack.Cleaned and deveined freshwater prawns (with tail) are gently tossed in a mixture of mildly spicy oils and seasonings. They're then batter-dipped, coated in a panko breadcrumb mixture and packed and sent to you! All you need to do is deep-fry them for 8 minutes, and serve! Super crispy on the outside and juicy on the inside.",
    Details:"Crumb-coated prawns, ready to be deep fried",
    Netwt:"200gms", 
    Pieces:"10-12",
    MRP:"332",
    MeatType:"Prawns",
   image1:"https://dao54xqhg9jfa.cloudfront.net/OMS-ProductMerchantdising/5d014683-86f6-348f-44c5-de5c5b9bbfc0/original/Crispy-Prawns---Hero-Cooked-Shot.jpg?format=webp",
   
},
{
    ProductId:"cook105",
    image:"https://dao54xqhg9jfa.cloudfront.net/OMS-ProductMerchantdising/242a6520-4fd9-692e-7708-5e09f0a96e43/original/Kozhi-Milagu-Varuval-(Chicken-Pepper-Dry)--Tag.jpg?format=webp",
    Title:"Chicken Pepper Dry | Ready To Cook",
    productPagedetails:"Kozhi Milagu Varuval (Chicken Pepper Dry) is a delicious snack or appetizer. This pack consists of pieces of freshly marinated bone-in chicken. Black pepper, shallots and ground salt come together in a moderately spicy marinade, to create a flavour bomb like none other.",
    Details:"Freshly marinated Bone-in chicken Moderately spicy",
    Netwt:"500gms", 
    Pieces:"10-13",
    MRP:"299",
    Cuisine:"South Indian",
   image1:"https://dao54xqhg9jfa.cloudfront.net/OMS-ProductMerchantdising/4c541888-7336-6447-61b1-fd4c1dd4946c/original/WhatsApp_Image_2022-06-07_at_4.04.14_PM_(3).jpeg?format=webp",
   image2:"https://dao54xqhg9jfa.cloudfront.net/OMS-ProductMerchantdising/ed3dc0c8-4e2d-db23-46f5-059fbb2f6cae/original/WhatsApp_Image_2022-06-07_at_11.56.17_PM.jpeg?format=webp"
},
{
    ProductId:"cook106",
    image:"https://d2407na1z3fc0t.cloudfront.net/prodDev/pr_15ckn5pzo5x/1/prod_display_image/1634616842.1144--2021-10-1909:44:02--1818",
    Title:"Assorted Kebab Platter | Ready to Cook",
    productPagedetails:"Indulge in our Nawabi-style kebabs during game days or get-togethers with friends or family. The platter consists of Afghani Murgh Seekh Kebab, Purani Dilli Mutton Seekh Kebab & Lucknowi Galouti Kebab - each ready within 8 minutes! The Kebabs are freshly marinated with authentic herbs & spices, chef crafted and have no artificial preservatives. They are hygienically vacuum packed & delivered at your doorstep. ",
    Details:"Tender &amp; juicy- our platter of kebabs is perfect for parties!",
    MRP:"899",
    PackSize:"Platter",
},
{
    ProductId:"cook107",
    image:"https://dao54xqhg9jfa.cloudfront.net/OMS-ProductMerchantdising/51a18a68-acc0-f766-e8a3-10529ac374ec/original/Chicken-Tangdi-Kebab-Tag.jpg?format=webp",
    Title:"Chicken Tangdi Kebab | Ready in 8 Minutes",
    productPagedetails:"Bring the flavours of the streets of Delhi home with the Chicken Tangdi Kebab that can be rustled up just 8 minutes. Chicken drumsticks are marinated in spices such as mace, fennel and cardamom and then pre-smoked and roasted over charcoal.",
    Details:"Chicken drumsticks in a smoky, spicy marinade.",
    Netwt:"300gms", 
    Pieces:"3",
    MRP:"249",
    SpiceLevel:"Medium",
   image1:"https://dao54xqhg9jfa.cloudfront.net/OMS-ProductMerchantdising/aad01c95-d6dd-e61a-b567-4f42d6f1cc8e/original/WhatsApp_Image_2022-06-07_at_1.09.43_PM_(4).jpeg?format=webp",
   
},
{
    ProductId:"cook108",
    image:"https://d2407na1z3fc0t.cloudfront.net/prodDev/pr_89lkrx2ojt1/1/prod_display_image/1634618320.6205--2021-10-1910:08:40--1818",
    Title:"Sichuan Chilli Chicken (Mini) | Ready to Cook",
    productPagedetails:"Boneless pieces of chicken, cut from the thigh are marinated in soy sauce, chilli paste & other spices, offering a classic Indo-Chinese flavour. These pieces can be pan-fried, grilled or baked and can be enjoyed as is or over a bowl of steamed rice. ",
    Details:"Mahi Mahi fish fillets, batter-dipped & crumb-coated",
    Netwt:"250gms", 
    Pieces:"10-12",
    MRP:"169",
    SpiceLevel:"Hot",
   image1:"https://d2407na1z3fc0t.cloudfront.net/prodDev/pr_89lkrx2ojt1/1/prod_image/1634618321.4015--2021-10-1910:08:41--1818",
   image2:"https://d2407na1z3fc0t.cloudfront.net/prodDev/pr_89lkrx2ojt1/1/prod_image/1634618325.5289--2021-10-1910:08:45--1818"
},
{
    ProductId:"cook109",
    image:"https://d2407na1z3fc0t.cloudfront.net/prodDev/pr_89lkrx2ojt1/1/prod_image/1634618325.5289--2021-10-1910:08:45--1818",
    Title:"Crispy Fish Fillet | Ready To Cook",
    productPagedetails:"A perfectly breaded, juicy fried fish is hard to get right, but our ready-to-fry Crispy Fish Fillets make it super easy for you!Mahi Mahi fillets are marinated in hot chilli seasoning, batter-dipped and then coated in panko breadcrumbs. They’re then packed into an airtight box and kept chilled, not frozen, through its journey to you.",
    Details:"Mahi Mahi fish fillets, batter-dipped &amp; crumb-coated",
    Netwt:"200gms", 
    Pieces:"3-4",
    MRP:"349",
    CutType:"Fillet",
   image1:"https://d2407na1z3fc0t.cloudfront.net/prodDev/pr_89lkrx2ojt1/1/prod_image/1634618325.5289--2021-10-1910:08:45--1818"
},
{
    ProductId:"cook110",
    image:"https://dao54xqhg9jfa.cloudfront.net/OMS-ProductMerchantdising/4d08a6f1-998d-66c8-16e7-fb9efec195ed/original/Afghani-Murgh-Seekh-Kebab(1).jpg?format=webp",
    Title:"Afghani Murgh Seekh Kebab | Ready in 8 Minutes",
    productPagedetails:"Meat minced from tender cuts of the chicken is shaped in to perfect ready-to-cook kebabs after it is mixed with spices and herbs. The authentic Afghani Murgh Seekh Kebab is ideal for pan-frying or grilling. When evenly cooked, the kebab turns charred on the outside and succulent on the inside. Order Afghani Murgh Seekh Kebabs from Licious and get them home delivered.",
    Details:"The classic chicken seekh kebab, marinated in traditional spices of the Mughal era.",
    Netwt:"400gms", 
    Pieces:"4",
    MRP:"249",
    CookingMethod:"Oven",
   image1:"https://d2407na1z3fc0t.cloudfront.net/prodDev/pr_89lkrx2ojt1/1/prod_image/1634618325.5289--2021-10-1910:08:45--1818"
},
{
    ProductId:"cook111",
    image:"The classic chicken seekh kebab, marinated in traditional spices of the Mughal era.",
    Title:"Piri Piri Cheese Chicken Burger Patty | Ready to Cook ",
    productPagedetails:"Spiced to perfection with our chef's special piri piri seasoning and flavoured with chunks of real cheese, our Piri Piri Cheese Chicken Burger Patty is spicy, cheesy and oh-so-juicy! Each pack contains 2 burger patties that have been hygienically packed to retain their shape and structure.",
    Details:"2 pieces of piri-piri flavoured chicken mince patties",
    Netwt:"250gms", 
    Pieces:"2-4",
    MRP:"199",
    CookingMethod:"PanFry",
   image1:"https://d2407na1z3fc0t.cloudfront.net/prodDev/pr_89lkrx2ojt1/1/prod_image/1634618325.5289--2021-10-1910:08:45--1818",
},
{
    ProductId:"cook112",
    image:"https://dao54xqhg9jfa.cloudfront.net/OMS-ProductMerchantdising/c20b4ac6-d97d-1b69-b71f-ddc57e8d68c5/original/WhatsApp_Image_2022-06-14_at_10.15.46_PM_(1).jpeg?format=webp",
    Title:"Chili & Cheese Lamb Burger Patty | Ready to Cook",
    productPagedetails:"Chef-crafted to spicy perfection, this burger patty is one of its kind! Flavoured with Thai chilli and real chunks of cheese, it's a spicy, cheesy and juicy delight crafted especially for all spice-lovers! Each pack consists of 2 burger patties that have been hygienically packed to ensure they're always fresh.",
    Details:"pieces of Chicken mince patties flavoured with butter ",
    Netwt:"250", 
    Pieces:"2",
    MRP:"349",
    Delivery:"Express Delivery",
   image1:"https://d2407na1z3fc0t.cloudfront.net/prodDev/pr_89lkrx2ojt1/1/prod_image/1634618325.5289--2021-10-1910:08:45--1818",
  
},


]